### ISSUE TITLE
Lead-ins section: There is no active state effect on the lead-ins.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/GKR-Transport#17]
IE7 and IE8 only

![image](https://cloud.githubusercontent.com/assets/11186313/6797379/29798132-d23c-11e4-9f7a-95f89bdc6cab.png)

**Comment by arielcebudigital** [comment]
I already ask stan about this, due to pie.js opacity will not effect inside the circle.

**Comment by roseliesromeo** [comment]
If opacity will have no effect, let's have it flat color on hover then

**Comment by arielcebudigital** [comment]
stanley already told that this is alright, if we make it flat color the image and title  will not be shown.

**Comment by roseliesromeo** [comment]
I've asked Leoman about this and he confirmed this should have hover with opacity.

**Comment by arielcebudigital** [comment]
ask leoman if opacity is  working on pie.js?, 
Our conversation 

yesterday i told you that i will push gkr so that you can see the IE7 and 8 in leadins
 Ariel Gallamaso: http://gkrtransport.stage.titanweb.com.au/
 Ariel Gallamaso: if it is ok without opacity..
stan: uhm you mean the opacity as in the hover effect?
Ariel:yes,,stan.. because of pie
stan:it's fine, no probs


You can confirm it to stan,

**Comment by leomanlapera** [comment]
opacity is working on PIE.js

Please refer to this documentation:
http://css3pie.com/demos/gradient-patterns/ if you notice their is -pie-background
